language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install -y pycodestyle
    - conda install -y matplotlib
    - conda install -y python-dateutil
    - conda install --yes python=3.6

script:
    - python test_avl_tree.py
    - python test_binary_tree.py
    - bash test_insert_key_value_pairs.sh
